<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatabaseBackup extends Command
{
    protected $signature = 'backup:database {--type=daily : daily|weekly|monthly}';
    protected $description = 'Create a database backup with retention management';

    private string $backupDir = 'backups';

    public function handle(): int
    {
        $type = $this->option('type');
        if (!in_array($type, ['daily', 'weekly', 'monthly'])) {
            $this->error("Invalid type: {$type}. Use daily, weekly, or monthly.");
            return Command::FAILURE;
        }

        $driver = DB::connection()->getDriverName();
        $backupDir = storage_path($this->backupDir);
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
        }

        $now    = Carbon::now('Asia/Manila');
        $stamp  = $now->format('Y-m-d_H-i-s');
        $dbName = $driver === 'sqlite'
            ? 'database'
            : (config('database.connections.mysql.database') ?: 'database');

        $filename = "{$dbName}_{$type}_{$stamp}.sql";
        $fullPath = "{$backupDir}/{$filename}";

        try {
            $dump = $driver === 'sqlite' ? $this->dumpSqlite() : $this->dumpMysql();
        } catch (\Throwable $e) {
            $this->error("Backup failed: {$e->getMessage()}");
            logger()->error('Database backup command failed', [
                'db' => $dbName,
                'type' => $type,
                'error' => $e->getMessage(),
            ]);
            return Command::FAILURE;
        }

        if ($dump === null || strlen($dump) < 1) {
            $this->error("Backup failed: dump was empty (exit code: unknown)");
            logger()->error('Database backup command failed', [
                'db' => $dbName,
                'type' => $type,
                'exit_code' => 'empty-dump',
            ]);
            return Command::FAILURE;
        }

        file_put_contents($fullPath, $dump);

        $size = $this->humanSize(filesize($fullPath));
        $this->info("✓ Backup created: {$fullPath} ({$size})");

        logger()->info('Database backup created', [
            'db' => $dbName,
            'type' => $type,
            'file' => $filename,
            'size' => $size,
        ]);

        // Enforce retention
        $this->enforceRetention($type);

        return Command::SUCCESS;
    }

    private function dumpSqlite(): string
    {
        $pdo = DB::connection()->getPdo();
        $out = "-- SQLite database dump generated by backup:database\n";
        $out .= "-- Date: " . Carbon::now('Asia/Manila')->toDateTimeString() . "\n\n";

        // Schema
        $stmt = $pdo->query("SELECT sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY type DESC, name");
        foreach ($stmt->fetchAll(\PDO::FETCH_COLUMN) as $sql) {
            $out .= $sql . ";\n";
        }

        // Data
        $tables = $pdo->query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
            ->fetchAll(\PDO::FETCH_COLUMN);

        foreach ($tables as $table) {
            $rows = $pdo->query("SELECT * FROM \"{$table}\"")->fetchAll(\PDO::FETCH_ASSOC);
            if (empty($rows)) {
                continue;
            }
            $cols = array_keys($rows[0]);
            $colList = implode(', ', array_map(fn ($c) => '"' . str_replace('"', '""', $c) . '"', $cols));
            $out .= "\n-- Data for {$table}\n";
            foreach ($rows as $row) {
                $values = array_map(function ($v) {
                    if ($v === null) {
                        return 'NULL';
                    }
                    if (is_numeric($v)) {
                        return $v;
                    }
                    return "'" . str_replace("'", "''", (string) $v) . "'";
                }, array_values($row));
                $out .= "INSERT INTO \"{$table}\" ({$colList}) VALUES (" . implode(', ', $values) . ");\n";
            }
        }

        return $out;
    }

    private function dumpMysql(): string
    {
        $dbName     = config('database.connections.mysql.database');
        $dbUser     = config('database.connections.mysql.username');
        $dbPassword = config('database.connections.mysql.password');
        $dbHost     = config('database.connections.mysql.host');

        $passwordArg = escapeshellarg($dbPassword);
        $cmd = sprintf(
            'MYSQL_PWD=%s mysqldump --host=%s --user=%s --single-transaction --routines --triggers --events %s 2>/dev/null',
            $passwordArg,
            escapeshellarg($dbHost),
            escapeshellarg($dbUser),
            escapeshellarg($dbName)
        );

        $output = [];
        $exitCode = 0;
        exec($cmd, $output, $exitCode);

        if ($exitCode !== 0) {
            return null;
        }

        return implode("\n", $output) . "\n";
    }

    private function enforceRetention(string $type): void
    {
        $keep = config("backup.retention.{$type}", 7);
        $dir  = storage_path($this->backupDir);
        if (!is_dir($dir)) {
            return;
        }

        // Collect all backup files for this type, sorted by modification time (newest first)
        $files = glob("{$dir}/*_{$type}_*.sql");
        usort($files, fn($a, $b) => filemtime($b) - filemtime($a));

        $deleted = 0;
        foreach (array_slice($files, (int) $keep) as $oldFile) {
            if (is_file($oldFile)) {
                unlink($oldFile);
                $deleted++;
            }
        }

        if ($deleted > 0) {
            $this->info("Retention: removed {$deleted} old backup(s), keeping {$keep} {$type}");
        }
    }

    private function humanSize(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $i = 0;
        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }
        return round($bytes, 2) . ' ' . $units[$i];
    }
}
