version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.php56
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'iwebphil_everlast'
      MYSQL_USER: 'helloworld_user'
      MYSQL_PASSWORD: 'p@ssw0rd_H3ll0W0rld!'
      MYSQL_ROOT_PASSWORD: 'root_password_change_me'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: