<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('receivables', function (Blueprint $table) {
            $table->id();
            $table->foreignId('agency_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); // encoder
            $table->foreignId('agent_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('applicant_id')->nullable()->constrained()->nullOnDelete();

            $table->string('code', 6);                    // autogenerated, unique per agency
            $table->date('date');
            $table->string('status', 20)->default('pending'); // pending | received

            $table->string('ref_ar', 100)->nullable();    // Ref#/AR#
            $table->decimal('amount', 12, 2)->default(0);

            // Account selection (per card)
            $table->string('account', 80)->nullable();
            // Payment Information
            $table->string('debit_account', 40)->nullable(); // Receivable | Dollar Request
            $table->string('type', 40)->nullable();           // Partial | Full Payment
            $table->string('mode', 40)->nullable();           // Cash|Cheque|Fund Transfer|Credit|GCash
            $table->text('particular')->nullable();

            $table->timestamps();

            // enforce uniqueness per agency (code is a 6-digit string)
            $table->unique(['agency_id', 'code']);

            $table->index(['agency_id', 'status']);
            $table->index(['agency_id', 'date']);
            $table->index('agent_id');
            $table->index('applicant_id');
        });

        Schema::create('receivable_histories', function (Blueprint $table) {
            $table->id();
            $table->foreignId('receivable_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); // actor
            $table->string('from_status', 20)->nullable();
            $table->string('to_status', 20)->nullable();
            $table->text('note')->nullable();
            $table->timestamps();

            $table->index('receivable_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('receivable_histories');
        Schema::dropIfExists('receivables');
    }
};
