<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Parent: one expense request per transaction
        Schema::create('expense_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('agency_id')->constrained()->cascadeOnDelete();
            $table->foreignId('user_id')->constrained('users')->cascadeOnDelete();
            // Reference code, autogenerated unique per agency
            $table->string('reference_no');
            $table->date('date');
            $table->string('status')->default('pending'); // pending|received
            $table->foreignId('branch_id')->nullable()->constrained('branches')->nullOnDelete();
            $table->text('notes')->nullable();
            $table->timestamps();

            $table->index('agency_id');
            $table->index(['agency_id', 'reference_no']);
        });

        // Lines: multiple items per expense request
        Schema::create('expense_request_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('expense_request_id')->constrained('expense_requests')->cascadeOnDelete();
            $table->enum('charge', ['office', 'agent']);
            $table->foreignId('agent_id')->nullable()->constrained('agents')->nullOnDelete();
            $table->foreignId('applicant_id')->nullable()->constrained('applicants')->nullOnDelete();
            $table->foreignId('country_id')->nullable()->constrained('countries')->nullOnDelete();
            $table->string('currency', 3)->default('PHP'); // PHP|USD
            $table->decimal('amount', 12, 2);
            $table->foreignId('account_id')->constrained('accounts')->cascadeOnDelete();
            $table->string('particular')->nullable();
            $table->string('file_path')->nullable(); // upload
            $table->timestamps();

            $table->index('expense_request_id');
            $table->index(['expense_request_id', 'charge']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('expense_request_items');
        Schema::dropIfExists('expense_requests');
    }
};
