<?php

function getCertificatesUpdateData($postData)
{
    return [
        'certificate_prc_type' => isset($postData['certificate_prc_type']) ? $postData['certificate_prc_type'] : null,
        'certificate_prc_rating' => isset($postData['certificate_prc_rating']) ? $postData['certificate_prc_rating'] : null,
        'certificate_prc_take' => isset($postData['certificate_prc_take']) ? $postData['certificate_prc_take'] : null,
        'certificate_saudi_id' => isset($postData['certificate_saudi_id']) ? $postData['certificate_saudi_id'] : null,
        'certificate_dha' => isset($postData['certificate_dha']) ? $postData['certificate_dha'] : null,
        'certificate_ksa' => isset($postData['certificate_ksa']) ? $postData['certificate_ksa'] : null,
        'certificate_haad' => isset($postData['certificate_haad']) ? $postData['certificate_haad'] : null,
        'certificate_qatar' => isset($postData['certificate_qatar']) ? $postData['certificate_qatar'] : null,
        'certificate_nclex' => isset($postData['certificate_nclex']) ? $postData['certificate_nclex'] : null,
        'certificate_nclex_exam' => isset($postData['certificate_nclex_exam']) ? $postData['certificate_nclex_exam'] : null,
        'certificate_ielts' => isset($postData['certificate_ielts']) ? $postData['certificate_ielts'] : null,
        'certificate_ielts_overall' => isset($postData['certificate_ielts_overall']) ? $postData['certificate_ielts_overall'] : null,
        'certificate_ielts_exam' => isset($postData['certificate_ielts_exam']) ? $postData['certificate_ielts_exam'] : null,
        'certificate_cgfns' => isset($postData['certificate_cgfns']) ? $postData['certificate_cgfns'] : null,
        'certificate_cgfns_id' => isset($postData['certificate_cgfns_id']) ? $postData['certificate_cgfns_id'] : null,
        'certificate_cgfns_exam' => isset($postData['certificate_cgfns_exam']) ? $postData['certificate_cgfns_exam'] : null,
        'certificate_vsh_exam' => isset($postData['certificate_vsh_exam']) ? $postData['certificate_vsh_exam'] : null,
        'swab' => isset($postData['swab']) ? $postData['swab'] : null,
        'swab_date' => isset($postData['swab_date']) ? $postData['swab_date'] : null,
        'mmr' => isset($postData['mmr']) ? $postData['mmr'] : null,
        'certificate_medical_clinic' => isset($postData['medical_clinic']) ? $postData['medical_clinic'] : null,
        'certificate_medical_exam_date' => isset($postData['medical_exam_date']) ? $postData['medical_exam_date'] : null,
        'medical_fit' => isset($postData['medical_fit']) ? $postData['medical_fit'] : null,
        'certificate_medical_result' => isset($postData['medical_result']) ? $postData['medical_result'] : null,
        'certificate_medical_remarks' => isset($postData['medical_remarks']) ? $postData['medical_remarks'] : null,
        'certificate_medical_expiration' => isset($postData['medical_expiration']) ? $postData['medical_expiration'] : null,
        'certificate_pt_result' => isset($postData['pt_result']) ? $postData['pt_result'] : null,
        'certificate_pt_result_date' => isset($postData['pt_result_date']) ? $postData['pt_result_date'] : null,
        'omma' => isset($postData['omma']) ? $postData['omma'] : null,
        'omma_date' => isset($postData['omma_date']) ? $postData['omma_date'] : null,
        'polio' => isset($postData['polio']) ? $postData['polio'] : null,
        'polio_date' => isset($postData['polio_date']) ? $postData['polio_date'] : null,
        'certificate_authenticated_nbi' => isset($postData['authenticated-nbi']) ? 1 : 0,
        'nbi_expired_date' => isset($postData['nbi-expired-date']) ? $postData['nbi-expired-date'] : null,
        'certificate_insurance' => isset($postData['insurance']) ? $postData['insurance'] : null,
        'insurance_no' => isset($postData['insurance-no']) ? $postData['insurance-no'] : null,
        'certificate_coe' => isset($postData['coe']) ? $postData['coe'] : null,
        'certificate_pdos' => isset($postData['pdos']) ? 1 : 0,
        'fra_pdos' => isset($postData['fra_pdos']) ? $postData['fra_pdos'] : null,
        'certificate_pdos_date' => isset($postData['pdos_date']) ? $postData['pdos_date'] : null,
        'certificate_pdos_no' => isset($postData['pdos_no']) ? $postData['pdos_no'] : null,
        'certificate_tesda' => isset($postData['tesda']) ? 1 : 0,
        'certificate_tesda_name' => isset($postData['tesda_name']) ? $postData['tesda_name'] : null,
        'certificate_tesda_date' => isset($postData['tesda_date']) ? $postData['tesda_date'] : null,
        'certificate_tesda_release' => isset($postData['tesda_release']) ? $postData['tesda_release'] : null,
        'certificate_tesda_assest' => isset($postData['certificate_tesda_assest']) ? $postData['certificate_tesda_assest'] : null,
    ];
}
