<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $reportTemplate->name }} — {{ $agency->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 8.5pt; color: #333; }

        .header {
            display: flex;
            align-items: center;
            gap: 12px;
            border-bottom: 2px solid #1a56db;
            padding-bottom: 10px;
            margin-bottom: 16px;
        }
        .header .logo {
            width: 56px;
            height: 56px;
            object-fit: contain;
        }
        .header .brand h1 {
            font-size: 14pt;
            color: #1a56db;
            margin-bottom: 2px;
        }
        .header .brand .info {
            font-size: 8pt;
            color: #666;
        }
        .title-section {
            margin-bottom: 12px;
        }
        .title-section h2 {
            font-size: 12pt;
            margin-bottom: 4px;
        }
        .title-section .meta {
            font-size: 7.5pt;
            color: #888;
        }
        table.data {
            width: 100%;
            border-collapse: collapse;
            font-size: 8pt;
        }
        table.data th {
            background: #1a56db;
            color: white;
            padding: 6px 8px;
            text-align: left;
            font-size: 7pt;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        table.data td {
            padding: 5px 8px;
            border-bottom: 1px solid #e5e7eb;
        }
        table.data tr:nth-child(even) td {
            background: #f9fafb;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 7pt;
            color: #aaa;
            border-top: 1px solid #e5e7eb;
            padding-top: 6px;
        }
        .footer .page-number:before { content: "Page "; }
        .footer .page-number:after { content: ""; }
    </style>
</head>
<body>
    <div class="header">
        @if($agency->logo)
            <img src="{{ storage_path('app/public/' . $agency->logo) }}" class="logo" alt="Logo" />
        @else
            <div class="logo" style="background:#1a56db;border-radius:50%;display:flex;align-items:center;justify-content:center;color:white;font-weight:bold;font-size:18pt;">{{ substr($agency->name, 0, 1) }}</div>
        @endif
        <div class="brand">
            <h1>{{ $agency->name }}</h1>
            <div class="info">{{ $agency->address ?? '' }} @if($agency->email) · {{ $agency->email }} @endif</div>
        </div>
    </div>

    <div class="title-section">
        <h2>{{ $reportTemplate->name }}</h2>
        <div class="meta">
            Type: {{ $reportTemplate->type }} · Generated: {{ now()->format('F d, Y h:i A') }} · {{ $rows->count() }} results
        </div>
    </div>

    <table class="data">
        <thead>
            <tr>
                <th>#</th>
                @foreach($columns as $col)
                    <th>{{ ['name'=>'Name','email'=>'Email','phone'=>'Phone','gender'=>'Gender','country'=>'Country','status'=>'Status','position'=>'Position','employer'=>'Employer','salary'=>'Salary','source'=>'Source','agent'=>'Agent','created_at'=>'Date Created','updated_at'=>'Last Updated'][$col] ?? ucfirst($col) }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $i => $row)
            <tr>
                <td style="color:#999;">{{ $i + 1 }}</td>
                @foreach($columns as $col)
                    <td>{{ $row[$col] ?? '' }}</td>
                @endforeach
            </tr>
            @empty
            <tr>
                <td colspan="{{ count($columns) + 1 }}" style="text-align:center;padding:40px;color:#999;">
                    No results found.
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by {{ $agency->name }} · {{ now()->format('Y-m-d H:i') }}
        <span class="page-number"></span>
    </div>
</body>
</html>
